---
- name: req2
  hosts: R2
  gather_facts: false
  connection: local

  tasks:
    - name: Load new ACL into device
      ios_config:
        parents: ip access-list extended REQ2
        lines:
          - 10 permit icmp echo 192.168.20.20 192.168.10.10
          - 20 permit icmp 192.168.20.20 any
          - 30 deny icmp any any
          - 40 permit ip any any

    - name: Apply new ACL to R1 Eth0/1
      ios_config:
        parents: int e0/1
        lines:
          - ip access-group REQ2 out

    - name: Check result
      ios_command:
        commands: sh ip access-lists REQ2
      register: result
      tags: show

    - name: Print result
      debug:
        var: result.stdout_lines
      tags: show
